# Generated by Django 5.0.4 on 2024-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqtable',
            name='option_a',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcqtable',
            name='option_b',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcqtable',
            name='option_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcqtable',
            name='option_d',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcqtable',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
