# Generated by Django 5.0.4 on 2024-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mcqtable_option_a_alter_mcqtable_option_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqtable',
            name='correct_answer',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
